---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-central
  namespace: movies
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: fortio
        image: fortio/fortio:1.63.0
        imagePullPolicy: IfNotPresent
        args: ["load", "-t", "0", "-qps", "500", "http://movieinfo.movies.svc.cluster.local/index.html"]
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
