---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieinfo-chi
  namespace: movies
  labels:
    app: movieinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movieinfo
  template:
    metadata:
      labels:
        app: movieinfo
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 50m
            memory: 50Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
        - name: movieinfo-config-chi
          mountPath: /usr/share/nginx/html
      volumes:
      - name: movieinfo-config-chi
        configMap:
          name: movieinfo-config-chi
          optional: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: movieinfo-config-chi
  namespace: movies
data:
  index.html: |
    <html>
    <h1>Movie information returned from the movieinfo-chi server!</h1>
    </br>
    </html>
