---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-east
  namespace: movies
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-east
        image: alpine/curl
        imagePullPolicy: IfNotPresent
        args: ["http://movieinfo.movies.svc.cluster.local/index.html"]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: topology.kubernetes.io/zone
                operator: In
                values: [east]
