---
apiVersion: v1
kind: Service
metadata:
  name: movieinfo
  namespace: movies
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - movieinfo-nyc
          - movieinfo-chi
          - movieinfo-lax
