---
apiVersion: v1
kind: Service
metadata:
  name: movieinfo
  namespace: movies
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    matchLabels:
      app: movieinfo
    matchExpressions:
      - {key: appzone, operator: In, values: [east, central, west]}
