external_services:
  prometheus:
    url: "http://prometheus.istio-system:9090/"
  grafana:
    auth:
      ca_file: ""
      insecure_skip_verify: true
      password: "pwd"
      token: ""
      type: "none"
      use_kiali_token: false
      username: "user"
    enabled: true
    internal_url: 'http://grafana.grafana:3000/'
    external_url: 'http://localhost:9001/grafana'
    dashboards:
    - name: "Istio Service Dashboard"
      variables:
        namespace: "var-namespace"
        service: "var-service"
    - name: "Istio Workload Dashboard"
      variables:
        namespace: "var-namespace"
        workload: "var-workload"
    - name: "Istio Mesh Dashboard"
    - name: "Istio Control Plane Dashboard"
    - name: "Istio Performance Dashboard"
    - name: "Istio Wasm Extension Dashboard"
    custom_dashboards:
      enabled: true
