deployment:
  cluster_wide_access: true
external_services:
  prometheus:
    url: "http://prometheus.istio-system:9090/"
  grafana:
    auth:
      ca_file: ""
      insecure_skip_verify: false
      password: ""
      token: ""
      type: "none"
      use_kiali_token: false
      username: ""
    enabled: true
    internal_url: 'http://grafana.grafana:3000/'
    external_url: 'http://localhost:9001/grafana'
    is_core: false
    dashboards:
    - name: "Istio Service Dashboard"
      variables:
        namespace: "var-namespace"
        service: "var-service"
    - name: "Istio Workload Dashboard"
      variables:
        namespace: "var-namespace"
        workload: "var-workload"
    - name: "Istio Mesh Dashboard"
    - name: "Istio Control Plane Dashboard"
    - name: "Istio Performance Dashboard"
    - name: "Istio Wasm Extension Dashboard"
  custom_dashboards:
    enabled: true
